# Generated by Django 4.2.4 on 2023-09-05 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options_room_paticipants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='paticipants',
            new_name='participants',
        ),
    ]
